run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Additional linters
    - bodyclose
    - dogsled
    - dupl
    - errorlint
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tparallel
    - unconvert
    - unparam
    - whitespace

  disable: []

linters-settings:
  govet:
    enable:
      - shadow

  errcheck:
    check-type-assertions: true
    check-blank: false
    exclude-functions:
      - (io.Closer).Close

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 150

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  funlen:
    lines: 100
    statements: 50

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/andrewhigh08/iam-service

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - hugeParam
      - rangeValCopy

  gosec:
    excludes:
      - G104 # Audit errors not checked
      - G304 # File path provided as taint input

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  godot:
    scope: declarations
    exclude:
      - "@Summary"
      - "@Description"
      - "@Tags"
      - "@Accept"
      - "@Produce"
      - "@Param"
      - "@Success"
      - "@Failure"
      - "@Router"
      - "@Security"

  stylecheck:
    checks:
      - all
      - -ST1000 # Package comments
      - -ST1003 # Naming

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - dupl
        - funlen
        - goconst
        - gosec
        - revive
        - gocyclo
        - errcheck
        - godot

    # Exclude linters for test packages
    - path: test/
      linters:
        - revive
        - errcheck
        - govet
        - godot

    # Exclude known linters from partially generated files
    - path: internal/adapter/repository/
      linters:
        - dupl

    # Exclude linter issues in main.go
    - path: cmd/api/main.go
      linters:
        - funlen

  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 3

severity:
  default-severity: warning
  rules:
    - linters:
        - gosec
      severity: error
    - linters:
        - govet
      severity: error
