// Code generated by MockGen. DO NOT EDIT.
// Source: internal/port/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/port/service.go -destination=test/mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/andrewhigh08/iam-service/internal/domain"
	port "github.com/andrewhigh08/iam-service/internal/port"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
	isgomock struct{}
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// ChangePassword mocks base method.
func (m *MockAuthService) ChangePassword(ctx context.Context, userID int64, oldPassword, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePassword", ctx, userID, oldPassword, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockAuthServiceMockRecorder) ChangePassword(ctx, userID, oldPassword, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockAuthService)(nil).ChangePassword), ctx, userID, oldPassword, newPassword)
}

// FirstTimePasswordChange mocks base method.
func (m *MockAuthService) FirstTimePasswordChange(ctx context.Context, userID int64, oldPassword, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstTimePasswordChange", ctx, userID, oldPassword, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// FirstTimePasswordChange indicates an expected call of FirstTimePasswordChange.
func (mr *MockAuthServiceMockRecorder) FirstTimePasswordChange(ctx, userID, oldPassword, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstTimePasswordChange", reflect.TypeOf((*MockAuthService)(nil).FirstTimePasswordChange), ctx, userID, oldPassword, newPassword)
}

// GenerateTokenForUser mocks base method.
func (m *MockAuthService) GenerateTokenForUser(ctx context.Context, userID int64) (*port.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTokenForUser", ctx, userID)
	ret0, _ := ret[0].(*port.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateTokenForUser indicates an expected call of GenerateTokenForUser.
func (mr *MockAuthServiceMockRecorder) GenerateTokenForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTokenForUser", reflect.TypeOf((*MockAuthService)(nil).GenerateTokenForUser), ctx, userID)
}

// GetPublicKey mocks base method.
func (m *MockAuthService) GetPublicKey() any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicKey")
	ret0, _ := ret[0].(any)
	return ret0
}

// GetPublicKey indicates an expected call of GetPublicKey.
func (mr *MockAuthServiceMockRecorder) GetPublicKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicKey", reflect.TypeOf((*MockAuthService)(nil).GetPublicKey))
}

// GetUserByEmail mocks base method.
func (m *MockAuthService) GetUserByEmail(ctx context.Context, email string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockAuthServiceMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockAuthService)(nil).GetUserByEmail), ctx, email)
}

// Login mocks base method.
func (m *MockAuthService) Login(ctx context.Context, email, password string) (*port.TokenPair, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password)
	ret0, _ := ret[0].(*port.TokenPair)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Login indicates an expected call of Login.
func (mr *MockAuthServiceMockRecorder) Login(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthService)(nil).Login), ctx, email, password)
}

// RefreshToken mocks base method.
func (m *MockAuthService) RefreshToken(ctx context.Context, refreshToken string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, refreshToken)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockAuthServiceMockRecorder) RefreshToken(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockAuthService)(nil).RefreshToken), ctx, refreshToken)
}

// Logout mocks base method.
func (m *MockAuthService) Logout(ctx context.Context, refreshToken, accessToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, refreshToken, accessToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthServiceMockRecorder) Logout(ctx, refreshToken, accessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthService)(nil).Logout), ctx, refreshToken, accessToken)
}

// LogoutAll mocks base method.
func (m *MockAuthService) LogoutAll(ctx context.Context, userID int64, accessToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogoutAll", ctx, userID, accessToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogoutAll indicates an expected call of LogoutAll.
func (mr *MockAuthServiceMockRecorder) LogoutAll(ctx, userID, accessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogoutAll", reflect.TypeOf((*MockAuthService)(nil).LogoutAll), ctx, userID, accessToken)
}

// IsTokenBlacklisted mocks base method.
func (m *MockAuthService) IsTokenBlacklisted(ctx context.Context, jti string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTokenBlacklisted", ctx, jti)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTokenBlacklisted indicates an expected call of IsTokenBlacklisted.
func (mr *MockAuthServiceMockRecorder) IsTokenBlacklisted(ctx, jti any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTokenBlacklisted", reflect.TypeOf((*MockAuthService)(nil).IsTokenBlacklisted), ctx, jti)
}

// ValidateToken mocks base method.
func (m *MockAuthService) ValidateToken(ctx context.Context, tokenString string) (*port.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", ctx, tokenString)
	ret0, _ := ret[0].(*port.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockAuthServiceMockRecorder) ValidateToken(ctx, tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockAuthService)(nil).ValidateToken), ctx, tokenString)
}

// GetUserSessions mocks base method.
func (m *MockAuthService) GetUserSessions(ctx context.Context, userID int64, currentTokenID string) ([]domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserSessions", ctx, userID, currentTokenID)
	ret0, _ := ret[0].([]domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserSessions indicates an expected call of GetUserSessions.
func (mr *MockAuthServiceMockRecorder) GetUserSessions(ctx, userID, currentTokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserSessions", reflect.TypeOf((*MockAuthService)(nil).GetUserSessions), ctx, userID, currentTokenID)
}

// RevokeSession mocks base method.
func (m *MockAuthService) RevokeSession(ctx context.Context, userID int64, tokenID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSession", ctx, userID, tokenID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeSession indicates an expected call of RevokeSession.
func (mr *MockAuthServiceMockRecorder) RevokeSession(ctx, userID, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSession", reflect.TypeOf((*MockAuthService)(nil).RevokeSession), ctx, userID, tokenID)
}

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// BlockUser mocks base method.
func (m *MockUserService) BlockUser(ctx context.Context, id, blockedBy int64, ipAddress, userAgent string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockUser", ctx, id, blockedBy, ipAddress, userAgent)
	ret0, _ := ret[0].(error)
	return ret0
}

// BlockUser indicates an expected call of BlockUser.
func (mr *MockUserServiceMockRecorder) BlockUser(ctx, id, blockedBy, ipAddress, userAgent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockUser", reflect.TypeOf((*MockUserService)(nil).BlockUser), ctx, id, blockedBy, ipAddress, userAgent)
}

// CreateUser mocks base method.
func (m *MockUserService) CreateUser(ctx context.Context, req *domain.CreateUserRequest, createdBy int64, ipAddress, userAgent string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, req, createdBy, ipAddress, userAgent)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserServiceMockRecorder) CreateUser(ctx, req, createdBy, ipAddress, userAgent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserService)(nil).CreateUser), ctx, req, createdBy, ipAddress, userAgent)
}

// GetUserByID mocks base method.
func (m *MockUserService) GetUserByID(ctx context.Context, id int64) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserServiceMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserService)(nil).GetUserByID), ctx, id)
}

// ListUsers mocks base method.
func (m *MockUserService) ListUsers(ctx context.Context, filter port.UserFilter) ([]domain.User, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, filter)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockUserServiceMockRecorder) ListUsers(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockUserService)(nil).ListUsers), ctx, filter)
}

// UnblockUser mocks base method.
func (m *MockUserService) UnblockUser(ctx context.Context, id, unblockedBy int64, ipAddress, userAgent string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnblockUser", ctx, id, unblockedBy, ipAddress, userAgent)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnblockUser indicates an expected call of UnblockUser.
func (mr *MockUserServiceMockRecorder) UnblockUser(ctx, id, unblockedBy, ipAddress, userAgent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnblockUser", reflect.TypeOf((*MockUserService)(nil).UnblockUser), ctx, id, unblockedBy, ipAddress, userAgent)
}

// MockAuthorizationService is a mock of AuthorizationService interface.
type MockAuthorizationService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorizationServiceMockRecorder
	isgomock struct{}
}

// MockAuthorizationServiceMockRecorder is the mock recorder for MockAuthorizationService.
type MockAuthorizationServiceMockRecorder struct {
	mock *MockAuthorizationService
}

// NewMockAuthorizationService creates a new mock instance.
func NewMockAuthorizationService(ctrl *gomock.Controller) *MockAuthorizationService {
	mock := &MockAuthorizationService{ctrl: ctrl}
	mock.recorder = &MockAuthorizationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorizationService) EXPECT() *MockAuthorizationServiceMockRecorder {
	return m.recorder
}

// AddRoleToUser mocks base method.
func (m *MockAuthorizationService) AddRoleToUser(ctx context.Context, userID int64, role string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRoleToUser", ctx, userID, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRoleToUser indicates an expected call of AddRoleToUser.
func (mr *MockAuthorizationServiceMockRecorder) AddRoleToUser(ctx, userID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRoleToUser", reflect.TypeOf((*MockAuthorizationService)(nil).AddRoleToUser), ctx, userID, role)
}

// CheckAccess mocks base method.
func (m *MockAuthorizationService) CheckAccess(ctx context.Context, userID int64, resource, action string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAccess", ctx, userID, resource, action)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAccess indicates an expected call of CheckAccess.
func (mr *MockAuthorizationServiceMockRecorder) CheckAccess(ctx, userID, resource, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAccess", reflect.TypeOf((*MockAuthorizationService)(nil).CheckAccess), ctx, userID, resource, action)
}

// GetUserRoles mocks base method.
func (m *MockAuthorizationService) GetUserRoles(ctx context.Context, userID int64) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRoles", ctx, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRoles indicates an expected call of GetUserRoles.
func (mr *MockAuthorizationServiceMockRecorder) GetUserRoles(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRoles", reflect.TypeOf((*MockAuthorizationService)(nil).GetUserRoles), ctx, userID)
}

// ReloadPolicies mocks base method.
func (m *MockAuthorizationService) ReloadPolicies(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReloadPolicies", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReloadPolicies indicates an expected call of ReloadPolicies.
func (mr *MockAuthorizationServiceMockRecorder) ReloadPolicies(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReloadPolicies", reflect.TypeOf((*MockAuthorizationService)(nil).ReloadPolicies), ctx)
}

// RemoveRoleFromUser mocks base method.
func (m *MockAuthorizationService) RemoveRoleFromUser(ctx context.Context, userID int64, role string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveRoleFromUser", ctx, userID, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveRoleFromUser indicates an expected call of RemoveRoleFromUser.
func (mr *MockAuthorizationServiceMockRecorder) RemoveRoleFromUser(ctx, userID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRoleFromUser", reflect.TypeOf((*MockAuthorizationService)(nil).RemoveRoleFromUser), ctx, userID, role)
}

// MockAuditService is a mock of AuditService interface.
type MockAuditService struct {
	ctrl     *gomock.Controller
	recorder *MockAuditServiceMockRecorder
	isgomock struct{}
}

// MockAuditServiceMockRecorder is the mock recorder for MockAuditService.
type MockAuditServiceMockRecorder struct {
	mock *MockAuditService
}

// NewMockAuditService creates a new mock instance.
func NewMockAuditService(ctrl *gomock.Controller) *MockAuditService {
	mock := &MockAuditService{ctrl: ctrl}
	mock.recorder = &MockAuditServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditService) EXPECT() *MockAuditServiceMockRecorder {
	return m.recorder
}

// GetUserAuditLogs mocks base method.
func (m *MockAuditService) GetUserAuditLogs(ctx context.Context, userID int64, limit int) ([]domain.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAuditLogs", ctx, userID, limit)
	ret0, _ := ret[0].([]domain.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAuditLogs indicates an expected call of GetUserAuditLogs.
func (mr *MockAuditServiceMockRecorder) GetUserAuditLogs(ctx, userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAuditLogs", reflect.TypeOf((*MockAuditService)(nil).GetUserAuditLogs), ctx, userID, limit)
}

// LogAction mocks base method.
func (m *MockAuditService) LogAction(ctx context.Context, userID int64, action, resourceType, resourceID string, details map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogAction", ctx, userID, action, resourceType, resourceID, details)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogAction indicates an expected call of LogAction.
func (mr *MockAuditServiceMockRecorder) LogAction(ctx, userID, action, resourceType, resourceID, details any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogAction", reflect.TypeOf((*MockAuditService)(nil).LogAction), ctx, userID, action, resourceType, resourceID, details)
}

// LogActionTx mocks base method.
func (m *MockAuditService) LogActionTx(ctx context.Context, tx *gorm.DB, userID int64, action, resourceType, resourceID string, details map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogActionTx", ctx, tx, userID, action, resourceType, resourceID, details)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogActionTx indicates an expected call of LogActionTx.
func (mr *MockAuditServiceMockRecorder) LogActionTx(ctx, tx, userID, action, resourceType, resourceID, details any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogActionTx", reflect.TypeOf((*MockAuditService)(nil).LogActionTx), ctx, tx, userID, action, resourceType, resourceID, details)
}

// LogActionWithContext mocks base method.
func (m *MockAuditService) LogActionWithContext(ctx context.Context, userID int64, action, resourceType, resourceID string, details map[string]any, ipAddress, userAgent string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogActionWithContext", ctx, userID, action, resourceType, resourceID, details, ipAddress, userAgent)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogActionWithContext indicates an expected call of LogActionWithContext.
func (mr *MockAuditServiceMockRecorder) LogActionWithContext(ctx, userID, action, resourceType, resourceID, details, ipAddress, userAgent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogActionWithContext", reflect.TypeOf((*MockAuditService)(nil).LogActionWithContext), ctx, userID, action, resourceType, resourceID, details, ipAddress, userAgent)
}

// LogActionWithContextTx mocks base method.
func (m *MockAuditService) LogActionWithContextTx(ctx context.Context, tx *gorm.DB, userID int64, action, resourceType, resourceID string, details map[string]any, ipAddress, userAgent string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogActionWithContextTx", ctx, tx, userID, action, resourceType, resourceID, details, ipAddress, userAgent)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogActionWithContextTx indicates an expected call of LogActionWithContextTx.
func (mr *MockAuditServiceMockRecorder) LogActionWithContextTx(ctx, tx, userID, action, resourceType, resourceID, details, ipAddress, userAgent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogActionWithContextTx", reflect.TypeOf((*MockAuditService)(nil).LogActionWithContextTx), ctx, tx, userID, action, resourceType, resourceID, details, ipAddress, userAgent)
}
